### ISSUE TITLE
Hanging function call indented to 4 spaces instead of 2

### ISSUE THREAD

**Issue by dhruvmanila** [JohnnyMorganz/StyLua#151]
First of all, amazing plugin. I started porting my Neovim config to lua and found myself in need of a good formatter. I tried others but, coming from Python using black, this was exactly what I needed. Just one nitpick: as mentioned in #133, I also prefer an optional parenthesis for one argument functions :)

For the following configuration:
```toml
column_width = 80
line_endings = "Unix"
indent_type = "Spaces"
indent_width = 2
quote_style = "AutoPreferDouble"
```

I get this formatting:
```lua
local output = Job
    :new({
    command = "stylua",
    args = { "-" },
    writer = api.nvim_buf_get_lines(bufnr, 0, -1, false),
  })
    :sync()
```

I don't know whether this is the preferred output but shouldn't the hanging method calls be indented to 2 spaces instead of 4? Could this be somehow related to what's being currently discussed in #123?
