### ISSUE TITLE
Misaligned tranformation for logical operators `and` and `or`

### ISSUE THREAD

**Issue by dhruvmanila** [JohnnyMorganz/StyLua#174]
For the following config:
```toml
column_width = 80
line_endings = "Unix"
indent_type = "Spaces"
indent_width = 2
quote_style = "AutoPreferDouble"
```

The output for the following line:
```lua
local long_variable_name = some_condition("testing") and condition_was_true(true) or condition_was_false(false)
```

is:
```lua
local long_variable_name = some_condition("testing")
    and condition_was_true(true)
  or condition_was_false(false)
```

The `and` and `or` is not lined up. Is this the expected way or is it a bug?
