### ISSUE TITLE
Multiple runs produces different output

### ISSUE THREAD

**Issue by dhruvmanila** [JohnnyMorganz/StyLua#181]
Configuration:
```toml
column_width = 80
line_endings = "Unix"
indent_type = "Spaces"
indent_width = 2
quote_style = "AutoPreferDouble"
```

The code in question is the long line:
```lua
print({ foo_variable = "some long value", foo_variable = "some long value", foo_variable = "some long value", })
```

First run produces:
```lua
print(
  {
    foo_variable = "some long value",
    foo_variable = "some long value",
    foo_variable = "some long value",
  }
)
```

Second and all the subsequent run produces:
```lua
print({
  foo_variable = "some long value",
  foo_variable = "some long value",
  foo_variable = "some long value",
})

```
Reference video:

https://user-images.githubusercontent.com/67177269/121357816-ba4add80-c94f-11eb-8d56-edad3a21d4ff.mov

Useful information: The formatting is done using stdin with this command `stylua --config-path <path> -` which is run on file save.
