### ISSUE TITLE
`pre-commit` doesn't appear to be working

### ISSUE THREAD

**Issue by Jarmos-san** [JohnnyMorganz/StyLua#410]
I've a couple of `.lua` files deeply nested within multiple folders. I ideally `stylua` should be able to simply identify them & format the files accordingly. But it doesn't seem to work in my case, `pre-commit` simply skips checking those files.

For more context, here's what the file structure is like for my project:

```
.
└── project-root /
    ├── lua-directory/
    │   ├── another-folder/
    │   │   ├── confs/
    │   │   │   ├── some.lua
    │   │   │   └── another.lua
    │   │   └── core/
    │   │       ├── random.lua
    │   │       └── utils.lua
    │   ├── more-folders/
    │   │   └── more-files.lua
    │   └── root.lua
    └── non-lua-directory/
        └── ...
```
... and Iconfigured `pre-commit` to use the system's `stylua`. Here's the `.pre-commit-config.yaml` file:

```yaml
repo:
    - repo: https://github.com/JohnnyMorganz/StyLua
      rev: v0.12.5
      hooks:
          - id: stylua-system
```
So, what am I doing wrong here?

**Comment by JohnnyMorganz** [comment]
I haven't really used pre-commit extensively, but everything you've mentioned so far seems fine to me - except the first line in your `.pre-commit-config.yaml` should be `repos:` rather than just `repo:`.

If there's still an issue, could you enable verbose logging, and see what the output looks like?
Something like this should enable it:
```yaml
repos:
    - repo: https://github.com/JohnnyMorganz/StyLua
      rev: v0.12.5
      hooks:
          - id: stylua-system
            args: [--verbose]
            verbose: true
```
