### ISSUE TITLE
Function calls break into multiple lines after 17 string concatenations 

### ISSUE THREAD

**Issue by dhruvmanila** [JohnnyMorganz/StyLua#432]
`.stylua.toml`:

```toml
column_width = 80
line_endings = "Unix"
indent_type = "Spaces"
indent_width = 2
quote_style = "AutoPreferSingle"
call_parentheses = "None"
```

Example code:
```lua
local function foo(...) end
local function long_function_name() end

local function test()
  return 'test'
    .. 'test'
    .. 'test'
    .. 'test'
    .. 'test'
    .. 'test'
    .. 'test'
    .. 'test'
    .. 'test'
    .. 'test'
    .. 'test'
    .. 'test'
    .. 'test'
    .. 'test'
    .. 'test'
    .. 'test'
    .. 'test'
    .. foo(long_function_name())
end
```

In the above example, concatenate another `'test'` and run the formatter. It will break the function call as:
```lua
local function foo(...) end
local function long_function_name() end

local function test()
  return 'test'
    .. 'test'
    .. 'test'
    .. 'test'
    .. 'test'
    .. 'test'
    .. 'test'
    .. 'test'
    .. 'test'
    .. 'test'
    .. 'test'
    .. 'test'
    .. 'test'
    .. 'test'
    .. 'test'
    .. 'test'
    .. 'test'
    .. 'test'
    .. foo(
      long_function_name()
    )
end
```

I don't know if it's a bug or not, but this seems like a weird edge case.
