### ISSUE TITLE
Removes newline between statements for multi-line concatenated strings

### ISSUE THREAD

**Issue by dhruvmanila** [JohnnyMorganz/StyLua#687]
`.stylua.toml`:

```toml
column_width = 80
line_endings = "Unix"
indent_type = "Spaces"
indent_width = 2
quote_style = "AutoPreferSingle"
call_parentheses = "None"
```

Example snippet:
```lua
local variable = 'this is a long string with multiple'
  .. 'different strings concatenated together'

local another_var = 1

local single_line_var = "hello"

local another = 2
```

When the above snippet is formatted, it removes the newline between the first and second variable assignment. Note that it doesn't remove the newline between the third and fourth assignment.

Reformatted (incorrectly):
```lua
local variable = 'this is a long string with multiple'
  .. 'different strings concatenated together'
local another_var = 1

local single_line_var = 'hello'

local another = 2
```
