### ISSUE TITLE
Question- Support ? and ` characters? 

### ISSUE THREAD

**Issue by Gellipapa** [JohnnyMorganz/StyLua#731]
Hi! I have a question: is there any way to make the formatter run longer if it finds these two characters somewhere?

The problem is I would use this formatting in code within the FiveM framework and they have solved it to use the optional ? and the backtick ` in lua and when I try to run the formatting I get an error that there is a syntax error, which is perfectly legitimate. 

I'll try to include it, but maybe you have a better idea how to do it. Probably if it could be solved many people would use it in the FiveM environment with a pretty large developer community.

What I'm thinking is that there might be some skip option that if you find one of these you can ignore.

Thanks for your reply in advance and great this formatting script is still :) 

Error message: 
![image](https://github.com/JohnnyMorganz/StyLua/assets/22717950/afb4ba76-526b-43cc-b7bb-d73678f96df4)

**Comment by matthargett** [comment]
This would need to be a feature added to the full-moon library. Can you file an issue in their repo and include a small code snippet that reproduces the issue?

**Comment by Gellipapa** [comment]
> This would need to be a feature added to the full-moon library. Can you file an issue in their repo and include a small code snippet that reproduces the issue?

Hi! I don't quite understand what this full-moon library means. Could you explain it better? 

On this link you can access the file you tried to format and find the error on line 162.
https://github.com/esx-framework/esx_core/blob/main/%5Bcore%5D/esx_multicharacter/server/main.lua

Workflow step:
```
      - name: Install stylua and format files
        uses: JohnnyMorganz/stylua-action@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          version: v0.18.0
          args: -- .
```

Thanks for the reply in advance.
