### ISSUE TITLE
Extend the `call_parentheses` option to allow separate configurations for strings and tables

### ISSUE THREAD

**Issue by lolmanurfunny** [JohnnyMorganz/StyLua#955]
Given the configuration options that are currently available, there's no way of enforcing a consistent style for single table calls, while at the same time never altering single string calls. If you could define them separately, then you could achieve this exact behavior given the following config: 
```toml
[call_parentheses]
single_table = "None" # Remove the parentheses from table calls,
single_string = "Input" # but don't touch my string calls!
```
